name: Build on Linux
on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
    runs-on: ${{ matrix.os }}
    env:
      ARCH: "${{ endsWith(matrix.os, 'arm') && 'aarch64' || 'x86_64' }}"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxkbcommon-dev libxkbcommon-x11-dev libx11-xcb-dev desktop-file-utils libasound2-dev libva-dev nvidia-cuda-dev
          rustup update
      - uses: Swatinem/rust-cache@v2
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Install libcontemporary utils
        run: |
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-bundle
          cargo install --git https://github.com/vicr123/contemporary-rs.git cargo-cntp-deploy
      - name: Build
        run: cargo build --verbose --release
      - name: Bundle
        run: cargo cntp-bundle
        working-directory: thegrid
      - name: Deploy
        run: cargo cntp-deploy --output-file "$HOME/theGrid-$ARCH.AppImage"
        working-directory: thegrid
      - uses: actions/upload-artifact@v4
        with:
          name: theGrid-linux-${{ env.ARCH }}
          path: "~/theGrid-${{ env.ARCH }}.AppImage"
